export const products = [
    {
      id: 1,
      image: "1",
      name: "Produto 1",
      price: 100,
      stock: 1,
      category: "a",
      createdAt: "x",
      updatedAt: "x",
    },
    {
      id: 2,
      image: "",
      name: "Produto 2",
      price: 200,
      stock: 2,
      category: "b",
      createdAt: "x",
      updatedAt: "x",
    },
    {
      id: 3,
      image: "",
      name: "Produto 3",
      price: 300,
      stock: 3,
      category: "c",
      createdAt: "x",
      updatedAt: "x",
    },
    {
      id: 4,
      image: "",
      name: "Produto 4",
      price: 400,
      stock: 4,
      category: "d",
      createdAt: "x",
      updatedAt: "x",
    },
    {
      id: 5,
      image: "",
      name: "Produto 5",
      price: 500,
      stock: 5,
      category: "e",
      createdAt: "x",
      updatedAt: "x",
    },
    {
      id: 6,
      image: "",
      name: "Produto 6",
      price: 600,
      stock: 6,
      category: "f",
      createdAt: "x",
      updatedAt: "x",
    },
    {
      id: 7,
      image: "",
      name: "Produto 7",
      price: 700,
      stock: 7,
      category: "g",
      createdAt: "x",
      updatedAt: "x",
    },
    {
      id: 8,
      image: "",
      name: "Produto 8",
      price: 800,
      stock: 8,
      category: "h",
      createdAt: "x",
      updatedAt: "x",
    },
  ]